export enum Model {
  LIGHT_WEIGHT = 'LIGHT_WEIGHT',
  MIDDLE_WEIGHT = 'MIDDLE_WEIGHT',
  CRUISER_WEIGHT = 'CRUISER_WEIGHT',
  HEAVY_WEIGHT = 'HEAVY_WEIGHT',
}

export enum State {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
  LOADED = 'LOADED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  RETURNING = 'RETURNING',
}
